### ISSUE TITLE
Utilize Environmental Variable DEPLOY_PLATFORM

### ISSUE THREAD

**Issue by graywolf336** [wedeploy-examples/rocketchat-example#5]
Hey there, thanks for this. What would be the chances you guys could set the environmental variable of `DEPLOY_PLATFORM=wedeploy`? This just helps us, the Rocket.Chat team, to visualize how people deploy their instance so we can provide support when needed.

**Comment by zenorocha** [comment]
Sure @graywolf336!

**Comment by graywolf336** [comment]
Thanks @zenorocha!
